"""Metric dictionary shared by API and documentation."""
CATALOG = [
 dict(name='vd.missing_packets',title='Pacchetti mancanti per evento NART',unit='packets',kind='event',source='[NARTn of Line m] Packet loss occurred … SN delta is … (N missing packets)',meaning='Numero esplicito di pacchetti segnalati come mancanti in un singolo salto della sequenza. Un punto isolato al timestamp del messaggio.',limits='Non è una percentuale RTCP, un contatore cumulativo o una perdita definitiva: riordino, arrivi tardivi e recupero possono modificare l’esito. Non sommare segnalazioni come pacchetti unici persi. Device, linea e sorgente restano separati; nessun SSRC viene inventato. Rotazioni con identico timestamp e identico messaggio sono deduplicate; numeri di sequenza diversi restano eventi distinti.'),
 dict(name='rtcp.rtt', title='RTT RTCP', unit='ms', kind='sample', source='RTT to this source: … ms; RTT by this source: … microseconds (÷1000)', meaning='Tempo di andata e ritorno riportato per la sorgente RTP/RTCP.', limits='Non è ritardo audio a senso unico. Può includere il percorso verso un relay/PBX. Un picco non localizza il guasto su un endpoint.'),
 dict(name='rtcp.jitter', title='Jitter RTCP', unit='ms', kind='sample', source='Jitter we perceive …; Receiver Report - jitter perceived by this remote peer …', meaning='Variabilità degli arrivi riportata localmente (incoming) o dal peer (outgoing).', limits='Separare direzioni, flow e SSRC. Non coincide con occupazione o target del buffer, né con il massimo VD.'),
 dict(name='rtcp.loss', title='Perdita RTCP', unit='%', kind='sample', source='Packet loss we perceive …; Receiver Report - remote peer pkt loss …', meaning='Percentuale di perdita riferita all’intervallo dichiarato dal report.', limits='Valori validi da 0 a 100. La media semplice dei report non è la perdita totale ponderata per pacchetti.'),
 dict(name='rtcp.packets_received', title='Pacchetti ricevuti', unit='packets', kind='counter', source='Packet we received from this source (total)', meaning='Contatore dei pacchetti ricevuti per sorgente.', limits='Può ripartire dopo reset/sessione. Non sommare campioni cumulativi né esportazioni dello stesso dispositivo.'),
 dict(name='network.ping', title='Ping ICMP', unit='ms', kind='sample', source='received … bytes … time=… ms', meaning='Tempo di andata e ritorno della sonda ICMP.', limits='La destinazione ICMP può differire dal peer multimediale. Non sostituisce RTT RTCP.'),
 dict(name='vd.max_arrival_delay', title='Massimo ritardo di arrivo NART', unit='ms', kind='event / gauge', source='m_maxPktArrivalTimeDelay to ms …; campo periodico m_maxPktArrivalTimeDelay (ms): …', meaning='Valore dichiarato dal motore per il massimo ritardo di arrivo. Nei WARNING è un aggiornamento del massimo.', limits='Il massimo può scendere quando il motore cambia finestra o stato. WARNING rappresentati come punti isolati: non sono campioni periodici del jitter.'),
 dict(name='vd.dejitter_target', title='Limite dinamico dejitter', unit='ms', kind='gauge', source='ring current max buffer usecs (for dynamic dejittering): … (÷1000)', meaning='Limite corrente del ring buffer nel device NART selezionato.', limits='Non è l’audio effettivamente in coda. Si escludono gli altri device per sezione, non per valore: 20000 µs su NART è un valido campione di 20 ms.'),
 dict(name='vd.buffer', title='Audio nel buffer NART', unit='ms', kind='gauge', source='buffer len in usecs: … (÷1000); Audio currently in buffer (ms): …', meaning='Durata dell’audio presente nel buffer di ricezione NART al momento del campione.', limits='È una misura locale, non il ritardo totale della chiamata. I due nomi sono alias empirici; il valore e l’unità originali restano nel DB.'),
 dict(name='vd.silence_skipped', title='Silenzio saltato cumulativo', unit='ms (grafico: ms o s)', kind='counter', source='silence usecs skipped so far: … (÷1000); silence msecs skipped so far: …', meaning='Durata cumulativa del silenzio saltato dichiarata dal device. Nel grafico si può scegliere ms oppure dividere ancora per 1000 per mostrare secondi.', limits='Non è perdita pacchetti né prova di voce persa. Può azzerarsi: non si presume continuità per tutta la chiamata.'),
 dict(name='derived.silence_delta', title='Incremento silenzio saltato', unit='ms', kind='interval', source='Differenza tra due campioni consecutivi di vd.silence_skipped, stessa prospettiva e device.', meaning='Quantità aggiuntiva nel periodo fra i due campioni; mostrata al timestamp del secondo.', limits='Il primo valore, un calo del contatore e un intervallo >30 s non producono delta. Non è un tasso al secondo. Entrambi gli eventi sono indicati come evidenza.'),
 dict(name='derived.buffer_sum', title='Somma dei buffer A+B', unit='ms', kind='derived gauge', source='Somma di vd.buffer dei due device scelti dopo correzione degli orologi; interpolazione lineare nei soli intervalli comuni.', meaning='Indicatore del buffering combinato dei due punti di vista, utile per confrontare gli andamenti.', limits='Non misura il ritardo end-to-end o conversazionale. Non include rete, codec o mixer; i due buffer ricevono direzioni diverse. Niente estrapolazione o interpolazione oltre 30 s. Servono due prospettive distinte, non due copie dello stesso dispositivo.'),
]
CATALOG.append(dict(name='derived.dejitter_sum',title='Somma dei limiti dinamici A+B',unit='ms',kind='derived gauge',source='Somma di vd.dejitter_target di A e B con interpolazione lineare solo nella copertura comune e con intervalli al massimo di 30 s.',meaning='Limiti dinamici combinati dei buffer di ricezione NART; distinto dalla somma dell’audio realmente in coda.',limits='Non è occupazione effettiva né misura di ritardo conversazionale. Nessuna estrapolazione; la selezione del periodo viene applicata prima della derivazione. Ogni punto conserva le evidenze dei campioni originali.'))
CATALOG.extend([
 dict(name='incident.buffer_underrun',title='Episodio di buffer underrun',unit='ms',kind='episode',source='Buffer underrun occurred; Still in buffer underrun … Event is currently … msecs; Buffer underrun event terminated … Event was … msecs long.',meaning='Periodo in cui l’osservatore non ottiene audio dal device NART selezionato. La durata dichiarata dal motore resta distinta dalla distanza fra timestamp dei messaggi.',limits='AWT (uscita audio) e VD (registrazione) sono osservatori separati: non sommare le loro durate. Senza inizio, un messaggio di fine con durata consente solo di ricavare l’inizio; senza fine l’episodio resta aperto. Contatori periodici e mutedReasons non vengono trasformati in episodi. Derivato su richiesta dagli eventi, non memorizzato in metrics.'),
 dict(name='incident.media_missing',title='Episodio di media missing',unit='ms (minimo stimato)',kind='episode',source='Line … reported that flow … has not received RTP media for more than … sec/ms; has re-started receiving RTP media / has started receiving RTP media again.',meaning='Assenza RTP segnalata su una linea e un flow. La soglia prima della segnalazione si aggiunge al tempo fino alla ripresa per stimare un limite inferiore della durata.',limits='L’inizio effettivo non è misurato: la barra parte dalla segnalazione meno la soglia. Il limite è ricavato dai messaggi e dipende dai tempi di notifica. Ripresa senza segnalazione precedente: durata sconosciuta. Nessuna chiusura viene inventata alla fine della chiamata. Eventi di coda media_missing e riepiloghi non duplicano gli episodi.')
])
for name, title, meaning in [
 ('audio.dtmf_rtt','RTT DTMF KPE','Statistica KPE denominata dtmf_rtt; semantica dettagliata da confermare col produttore.'),
 ('audio.jitter','Jitter KPE','Statistica del motore denominata jitter.'),
 ('audio.jitter_rfc3550','Jitter RFC3550 KPE','Statistica del motore etichettata jitter_rfc3550.'),
 ('audio.ploss_jitter','Perdita jitter KPE','Statistica del motore denominata ploss_jitter; non equiparata automaticamente alla perdita RTCP.'),
 ('common.ploss','Perdita KPE','Statistica del motore denominata ploss.'),
 ('common.rtt','RTT KPE','Statistica del motore denominata rtt.'),
 ('common.rtp_pkt_rx','Pacchetti RX KPE','Conteggio RTP ricevuto dichiarato dal motore.'),
 ('common.rtp_pkt_tx','Pacchetti TX KPE','Conteggio RTP trasmesso dichiarato dal motore.')]:
 CATALOG.append(dict(name='kpe.'+name,title=title,unit='packets' if 'rtp_pkt' in name else 'raw',kind='reported statistic',source='JSON incoming/outgoing → '+name.replace('.', ' → ')+' → last/avg/min/max',meaning=meaning,limits='last/avg/min/max restano distinti; finestra statistica e unità non dichiarate non vengono dedotte. Le metriche raw non entrano nel grafico in millisecondi. Valori non numerici, NaN e infinito non diventano zero.'))


CATALOG.append(dict(name='derived.mos_reference',title='MOS a profilo fisso · sola perdita',unit='MOS',kind='derived step',source='Perdita RTCP (%) locale o dichiarata dal peer. Profilo loss-reference-1: G.711 10 ms, PLC Appendix I, Ie=0, Bpl=25.1, BurstR=1, R base=93.2.',meaning='Indice stimato a profilo costante per confrontare la perdita nelle due direzioni. R=93.2−95p/(p+25.1), limitato a 0–100; MOS=1+0.035R+0.000007R(R−60)(100−R).',limits='Non è qualità vocale misurata né E-model completo. Non valuta jitter, ritardo, scarti, burst o PLC reale. Il report riguarda il passato; il valore viene mantenuto al massimo 30 s fino al report successivo o alla fine chiamata. Report invalidi o discordanti interrompono la curva. Nel pannello MOS il peer è scelto esplicitamente e la sua ricezione locale è riutilizzata. Riferimenti: ITU-T G.107 (2015), G.113 (2024) tabella I.4.'))


def catalog(db):
 result = list(CATALOG)
 known = {x['name'] for x in result}
 for row in db.execute('SELECT DISTINCT name,unit FROM metrics ORDER BY name'):
  if row['name'] not in known:
   result.append(dict(name=row['name'],title=row['name'],unit=row['unit'],kind='reported statistic',source='Campo numerico estratto dal log; consultare evento originale.',meaning='Metrica non ancora documentata individualmente.',limits='Semantica e unità non confermate: nessuna diagnosi automatica.'))
   known.add(row['name'])
 return result
